# text = input("Enter some text:")
# print(text)
# number=int(input("Enter anything:"))
# print(number)
# fnum=float(input("Enter anything:"))
# print(fnum)
# btext=bool(input("Enter something:"))
# print(btext)
a=int(input("a="))
b=int(input("b="))
print("a+b=",a+b)
print("a-b=",a-b)
print("a*b=",a*b)
print("a/b=",a/b)
print("a//b=",a//b)
print("a % b=",a%b)
print("a**b=",a**b)